# Generated by Django 5.2.6 on 2025-09-28 23:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fila",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "sigla",
                    models.CharField(
                        help_text="Ex: 'N' para Normal, 'P' para Prioritário",
                        max_length=3,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Senha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_senha", models.PositiveIntegerField()),
                (
                    "data_emissao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGU", "Aguardando"),
                            ("CHA", "Chamada"),
                            ("FIN", "Finalizada"),
                        ],
                        default="AGU",
                        max_length=3,
                    ),
                ),
                (
                    "fila",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.fila"
                    ),
                ),
            ],
            options={
                "unique_together": {("fila", "numero_senha")},
            },
        ),
    ]
