# Generated by Django 5.2.6 on 2025-10-22 23:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fila",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "sigla",
                    models.CharField(
                        help_text="Ex: 'N' para Normal, 'P' para Prioritário",
                        max_length=3,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(max_length=11, unique=True, verbose_name="CPF"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Senha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_senha", models.PositiveIntegerField()),
                (
                    "data_emissao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGU", "Aguardando"),
                            ("CHA", "Chamada"),
                            ("ATE", "Em Atendimento"),
                            ("FIN", "Finalizada"),
                        ],
                        default="AGU",
                        max_length=3,
                    ),
                ),
                ("hora_chamada", models.DateTimeField(blank=True, null=True)),
                (
                    "hora_inicio_atendimento",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("hora_fim_atendimento", models.DateTimeField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "atendente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="senhas_atendidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atendente",
                    ),
                ),
                (
                    "fila",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.fila"
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("fila", "numero_senha")},
            },
        ),
        migrations.CreateModel(
            name="Historico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio_atendimento", models.DateTimeField()),
                ("data_fim_atendimento", models.DateTimeField(auto_now_add=True)),
                (
                    "atendente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atendimentos_realizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "senha",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.senha"
                    ),
                ),
            ],
        ),
    ]
