# Generated by Django 5.2.6 on 2025-10-09 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_senha_paciente"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="senha",
            name="data_chamada",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Historico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio_atendimento", models.DateTimeField()),
                ("data_fim_atendimento", models.DateTimeField(auto_now_add=True)),
                (
                    "atendente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atendimentos_realizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "senha",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.senha"
                    ),
                ),
            ],
        ),
    ]
